version: '3'
services:
  postgres-master:
    image: 'bitnami/postgresql'
    restart: always
    container_name: 'postgres-master'
    environment:
      - 'TZ=Asia/Shanghai'
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=123456'
      - 'POSTGRES_DB=colago'
      - 'POSTGRESQL_REPLICATION_MODE=master'
      - 'POSTGRESQL_REPLICATION_USER=colago'
      - 'POSTGRESQL_REPLICATION_PASSWORD=colago'
    ports:
      - '9432:5432'
    networks:
      - custom_net
    volumes:
      - '/d/docker-root/data/postgres-master/data:/var/lib/postgresql/data'
  postgres-slave1:
    image: 'bitnami/postgresql'
    restart: always
    container_name: 'postgres-slave1'
    environment:
      - 'TZ=Asia/Shanghai'
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=123456'
      - 'POSTGRES_DB=colago'
      - 'POSTGRESQL_REPLICATION_MODE=slave'
      - 'POSTGRESQL_REPLICATION_USER=colago'
      - 'POSTGRESQL_REPLICATION_PASSWORD=colago'
      - 'POSTGRESQL_MASTER_HOST=postgres-master'
      - 'POSTGRESQL_MASTER_PORT_NUMBER=5432'
    links:
      - 'postgres-master'
    ports:
      - '9433:5432'
    networks:
      - custom_net
    volumes:
      - '/d/docker-root/data/postgres-slave1/data:/var/lib/postgresql/data'
  postgres-slave2:
    image: 'bitnami/postgresql'
    restart: always
    container_name: 'postgres-slave2'
    environment:
      - 'TZ=Asia/Shanghai'
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=123456'
      - 'POSTGRES_DB=colago'
      - 'POSTGRESQL_REPLICATION_MODE=slave'
      - 'POSTGRESQL_REPLICATION_USER=colago'
      - 'POSTGRESQL_REPLICATION_PASSWORD=colago'
      - 'POSTGRESQL_MASTER_HOST=postgres-master'
      - 'POSTGRESQL_MASTER_PORT_NUMBER=5432'
    links:
      - 'postgres-master'
    ports:
      - '9434:5432'
    networks:
      - custom_net
    volumes:
      - '/d/docker-root/data/postgres-slave2/data:/var/lib/postgresql/data'
networks:
  custom_net:
   external:
      name: app_net