version: '3'

services:
  consul-ui:
    image: 'consul:latest'
    container_name: 'consul-ui'
    ports:
      - '8500:8500'
    command: 'agent -server -ui -client=0.0.0.0 -node=consul-ui -data-dir /tmp/consul'
    networks:
      - custom_net
    volumes:
      - './data/consul-ui:/tmp/consul'

  postgres-master:
    image: 'bitnami/postgresql'
    container_name: 'postgres-master'
    environment:
      - 'TZ=Asia/Shanghai'
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=123456'
      - 'POSTGRES_DB=colago'
      - 'POSTGRESQL_REPLICATION_MODE=master'
      - 'POSTGRESQL_REPLICATION_USER=colago'
      - 'POSTGRESQL_REPLICATION_PASSWORD=colago'
    ports:
      - '5432:5432'
    networks:
      - custom_net
    volumes:
      - './data/postgres-master:/bitnami/postgresql'

  otel-collector:
    image: 'otel/opentelemetry-collector-contrib:latest'
    command: ["--config=/etc/otel-collector-config.yaml", "--log-level=DEBUG"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./data/otel:/root/log
    ports:
      - "1888:1888"   # pprof extension
      - "13133:13133" # health_check extension
      - "4317"        # OTLP gRPC receiver
      - "55670:55679" # zpages extension
    networks:
      - custom_net

networks:
  custom_net:
   external:
      name: app_net